<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="smartSLA" nsURI="http://www.example.org/smartSLA" nsPrefix="smartSLA">
  <eClassifiers xsi:type="ecore:EClass" name="SLAContract">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="duration" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="version" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parties" lowerBound="2"
        upperBound="-1" eType="#//Party" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="objectives" lowerBound="1"
        upperBound="-1" eType="#//ServiceObjective" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="penalties" upperBound="-1"
        eType="#//Penalty" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="notifications" upperBound="-1"
        eType="#//Notification" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="compliancerequirements"
        upperBound="-1" eType="#//ComplianceRequirement" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="securityrequirements" upperBound="-1"
        eType="#//SecurityRequirement" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="auditLogs" upperBound="-1"
        eType="#//SLAHistory" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="versioncontrol" eType="#//VersionControl"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="incentives" upperBound="-1"
        eType="#//Incentive" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="terminationConditions"
        upperBound="-1" eType="#//TerminationCondition" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="disputeresolution" eType="#//DisputeResolution"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="changerequest" upperBound="-1"
        eType="#//ChangeRequest" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="escalationpolicy" upperBound="-1"
        eType="#//EscalationPolicy" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Party" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="role" eType="#//Role"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="address" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="reputationScore" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="changerequest" lowerBound="1"
        eType="#//ChangeRequest" eOpposite="#//ChangeRequest/party"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ServiceObjective">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metric" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="threshold" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="measurementUnit" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="evaluationMethod" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cloudsource" lowerBound="1"
        eType="#//CloudSource" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Penalty">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="condition" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="action" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="enforcementMechanism" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Incentive">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="condition" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="reward" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TerminationCondition">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="reason" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="consequence" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DisputeResolution">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="procedure" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mediator" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="jurisdiction" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ChangeRequest">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="status" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="timestamp" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="party" lowerBound="1" eType="#//Party"
        eOpposite="#//Party/changerequest"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EscalationPolicy">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="level" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="action" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="responseTime" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Notification">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="triggerCondition" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="message" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//Party"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ComplianceRequirement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="standard" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="verificationMethod" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SecurityRequirement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="encryptionLevel" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="accessControl" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="auditTrail" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SLAHistory">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="timestamp" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eventType" eType="#//EventType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="details" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VersionControl">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="versionNumber" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="changeLog" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="timestamp" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Role">
    <eLiterals name="Provider"/>
    <eLiterals name="Consumer" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CloudSource">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//CloudSourceType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="identifier" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="provider" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="CloudSourceType">
    <eLiterals name="VM"/>
    <eLiterals name="Storage" value="1"/>
    <eLiterals name="Network" value="2"/>
    <eLiterals name="Database" value="3"/>
    <eLiterals name="DisasterRecoverySystem" value="4"/>
    <eLiterals name="IoTDevice" value="5"/>
    <eLiterals name="IoTDataPlatform" value="6"/>
    <eLiterals name="ServerlessFunction" value="7"/>
    <eLiterals name="ServerlessPlatform" value="8"/>
    <eLiterals name="AnalyticsEngine" value="9"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="EventType">
    <eLiterals name="Violation"/>
    <eLiterals name="Compliance" value="1"/>
    <eLiterals name="Update" value="2"/>
    <eLiterals name="Breach" value="3"/>
    <eLiterals name="Performance Alert" value="4" literal="Performance Alert"/>
    <eLiterals name="DRTest" value="5" literal="DRTest"/>
    <eLiterals name="DataAccuracyAlert" value="6"/>
    <eLiterals name="AnalyticsAlert" value="7"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NamedElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
